version: "2.4"

services:
  mail:
    build: .
    volumes:
      - ./config:/go/src/github.com/RiiConnect24/Mail-Go/config
    ports:
      # Container 80 -> Host 8080
      - "8080:80"
    restart: on-failure
    network_mode: "host"
    cpu_percent: 25
    mem_limit: 2048000000
volumes:
  mail_data:
