version: "3"

services:
  mail:
    build: .
    volumes:
      - ./config:/go/src/github.com/RiiConnect24/Mail-Go/config
    ports:
      # Container 80 -> Host 8080
      - "8080:80"
    restart: on-failure
    network_mode: "host"
volumes:
  mail_data:
